### ISSUE TITLE
Please repair assets

### ISSUE THREAD

**Issue by Jurix** [contributte/datagrid#704]
Hi, 
datagrid/assets/dist/datagrid.css contains CSS directives for spinners instead of datagrid directives. 

thanks

**Comment by f3l1x** [comment]
Fixed. Could you test it please?

**Comment by Jurix** [comment]
Thank you, code looks better now. However I still cannot make it work with Bootstrap 4. 
All assets included but some elements doesn't look good (as you can see in attached screenshot). 
Any suggestion?

![screenshot_datagrid](https://user-images.githubusercontent.com/9659882/46612092-e57e2e80-cb0f-11e8-87d9-2bc8a1427fc4.jpg)

**Comment by Jurix** [comment]
Now it is all right, thank you
