### ISSUE TITLE
Filters and new trigger handling in Nette 3.1

### ISSUE THREAD

**Issue by milsorm** [contributte/datagrid#945]
Combination of setFilterSelect and Nette 3.1 leads to warning:

Nette\Forms\Container::getValues() invoked but the form is not valid

which is generated Nete\Forms\Container::getValues as new trigger_error in 3.1. Inside form is invalid control with that filter.

If I suppress that trigger (or $form-getValues() in DataGrid::filterSucceeded (via @) everything works fine. But that means to put something into vendor code and that is not pretty :(

Test on latest dev-master branch.

**Comment by milsorm** [comment]
This is also BC break with getValues probably.

**Comment by paveljanda** [comment]
This should be fixed in last release 👍

**Comment by milsorm** [comment]
Still not working  in 6.8.1:

Nette\Forms\Container::getValues() invoked but the form is not valid.

**Comment by paveljanda** [comment]
@milsorm Can you show me the Tracy bluescreen + describe, how did you achieve it? Thanks

**Comment by milsorm** [comment]
Using latest Nette Forms and head of repository for datagrid.

Using standard TextFilter:

```
	public function addColumnTextSortableFilterable ( string $name, string $label, ...$args ): ColumnText {
		$col = $this->addColumnText( $name, $label, ...$args )
					->setSortable()->setSortableResetPagination();
		$col->setFilterText();

		return $col;
	}
```

and using

`		$grid->addColumnTextSortableFilterable( 'jmeno', 'Jméno' );
`

and blue screen:

![image](https://user-images.githubusercontent.com/6371213/111903871-6f9e8100-8a44-11eb-9210-79420bbdc562.png)

**Comment by milsorm** [comment]
Prrfectly working with nette/forms before BC break.

**Comment by milsorm** [comment]
And if I put @ to suppress warning before that line everything works. So only issue is that warning.

**Comment by milsorm** [comment]
Suppression in PR #969 
Not solving, but helping to use new features together with nette/forms 3.1

**Comment by arwin009** [comment]
Hello!

I have several datagrids in my application and I also encountered this error on some of them. In my case, I can see this error on datagrids with "Inline add" functionality.

This also causes another problem in one of the datagrids: When some filters are active and I change the count of items on the page via paginator, then the result is not filtered. I have to do a page refresh to get correct results.

I was able to resolve these problems when I changed this line:
https://github.com/contributte/datagrid/blob/527ab9570638d43be452799f144cad9612567a5a/src/DataGrid.php#L1494

into this:
`$values = (array) $form->getUnsafeValues(null);`


Hope it helps someone :)

**Comment by s1t2e3** [comment]
Still not working in datagrid v.6.9.0 nette/form v3.1.4

**Comment by dakorpar** [comment]
@paveljanda @f3l1x This also happens in some ocasion to me, I see it in logs, can someone take a look and solve it?

**Comment by f3l1x** [comment]
@dakorpar Is this patch working for your? 

https://github.com/contributte/datagrid/pull/969/files
